### PR TITLE
import the android plugin classpath, should make tests pass

### PR DESCRIPTION
**Pull request by martinbonnin**
Inspired by https://github.com/square/sqldelight/blob/83145b28cbdd949e98e87819299638074bd21147/sqldelight-gradle-plugin/build.gradle#L18

### CODE REVIEW

**Comment by tasomaniac** [comment]
Oh wow. Opening a PR onto my fork. Thanks for the effort. This looks good. I am going to use this actually with another plugin. I've been struggling with this for a while.

**Comment by martinbonnin** [comment]
You're super fast ! :zap:  I was still trying to write a message in the other thread :). Also I wanted to credit SQL Delight somewhere in the comment if you can add a note or so ? That'll also serve as future reference.

**Comment by tasomaniac** [comment]
Sorry. I was really curious what the CI will say about this change 😅 I'm waiting for my flight and have nothing else to do. 🙄 I should watch some TV shows instead

**Comment by martinbonnin** [comment]
:-). No worries, I'm very eager about the CI results too ! Have a good flight !! :airplane:

**Pull request merged**
